<?php

use Illuminate\Database\Seeder;

class StaffTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('staff')->insert([
            [
                'sn'               => 0,
                'mobile'           => 'root',
                'mobile_confirmed' => true,
                'org'              => 1,
                'department'       => 1,
                'position'         => 1,
                'gender'           => 1,
                'name'             => '系统管理者',
                'name_en'          => 'Root User',
                'password'         => bcrypt('000000'),
                'locked'           => false,
                'hide'             => true,
                'new'              => false,
                'root'             => true,
                'admin'            => false,
                'locked'           => false,
                'content'          => '',
                'content_en'       => '',
                'created_by'       => 1,
                ],[
                'sn'               => 1,
                'mobile'           => '15305297100',
                'mobile_confirmed' => true,
                'org'              => 1,
                'department'       => 4,
                'position'         => 3,
                'gender'           => 1,
                'name'             => '周建超',
                'name_en'          => 'amose',
                'password'         => bcrypt('000000'),
                'locked'           => false,
                'hide'             => false,
                'new'              => false,
                'root'             => false,
                'admin'            => false,
                'locked'           => false,
                'content'          => '管理员',
                'content_en'       => 'Root User',
                'created_by'       => 1,
                ],[
                'sn'               => 2,
                'mobile'           => '13951195320',
                'mobile_confirmed' => true,
                'org'              => 1,
                'department'       => 9,
                'position'         => 5,
                'gender'           => 2,
                'name'             => '仲依玲',
                'name_en'          => 'bella',
                'password'         => bcrypt('000000'),
                'locked'           => false,
                'hide'             => false,
                'new'              => true,
                'root'             => false,
                'admin'            => false,
                'locked'           => false,
                'content'          => '运营部总监',
                'content_en'       => '',
                'created_by'       => 1,
                ],[
                'sn'               => 3,
                'mobile'           => '13986621106',
                'mobile_confirmed' => true,
                'org'              => 1,
                'department'       => 6,
                'position'         => 6,
                'gender'           => 2,
                'name'             => '周秀华',
                'name_en'          => 'Ert',
                'password'         => bcrypt('000000'),
                'locked'           => false,
                'hide'             => false,
                'new'              => true,
                'root'             => false,
                'admin'            => false,
                'locked'           => false,
                'content'          => '市场部经理',
                'content_en'       => '',
                'created_by'       => 1,
                ],[
                'sn'               => 5,
                'mobile'           => '13901752021',
                'mobile_confirmed' => true,
                'org'              => 1,
                'department'       => 5,
                'position'         => 4,
                'gender'           => 1,
                'name'             => '倪昌盛',
                'name_en'          => 'kris',
                'password'         => bcrypt('000000'),
                'locked'           => false,
                'hide'             => false,
                'new'              => true,
                'root'             => true,
                'admin'            => false,
                'locked'           => false,
                'content'          => '副总',
                'content_en'       => '',
                'created_by'       => 1,
                ],[
                'sn'               => 6,
                'mobile'           => '15298340938',
                'mobile_confirmed' => true,
                'org'              => 1,
                'department'       => 8,
                'position'         => 5,
                'gender'           => 1,
                'name'             => '孙建',
                'name_en'          => 'Joyce',
                'password'         => bcrypt('000000'),
                'locked'           => false,
                'hide'             => false,
                'new'              => true,
                'root'             => false,
                'admin'            => true,
                'locked'           => false,
                'content'          => '技术总监',
                'content_en'       => '',
                'created_by'       => 1,
                ],[
                'sn'               => 1000,
                'mobile'           => '18451818180',
                'mobile_confirmed' => false,
                'org'              => 10,
                'department'       => 15,
                'position'         => 7,
                'gender'           => 1,
                'name'             => '小王',
                'name_en'          => 'Billy',
                'password'         => bcrypt('000000'),
                'locked'           => false,
                'hide'             => false,
                'new'              => true,
                'root'             => false,
                'admin'            => false,
                'locked'           => false,
                'content'          => '建设路负责人',
                'content_en'       => '',
                'created_by'       => 1,
                ],[
                'sn'               => 1001,
                'mobile'           => '13812591191',
                'mobile_confirmed' => true,
                'org'              => 10,
                'department'       => 14,
                'position'         => 9,
                'gender'           => 2,
                'name'             => '小芳',
                'name_en'          => 'Ella',
                'password'         => bcrypt('000000'),
                'locked'           => false,
                'hide'             => false,
                'new'              => true,
                'root'             => false,
                'admin'            => false,
                'locked'           => false,
                'content'          => '人民路员工',
                'content_en'       => '',
                'created_by'       => 1,
            ],
        ]);
    }
}


